#============ VerifyMe ============#

# Should Forum Verification be enabled? Note, if you enabled this then you MUST fill out all forum-related configuration options.
ForumVerification: true

# The URL of the forums.
ForumURL: ''

# The username and password for the forum bot account.
ForumUsername: ''
ForumPassword: ''

# Should Discord Verification be enabled? Note, if you enabled this then you MUST fill out all discord-related configuration options.
DiscordVerification: true

# The token for the discord bot.
DiscordBotToken: ''

# Whether or not to enable debug messages.
DebugMessages: false