#============ VerifyMe ============#

# The URL of the forums.
ForumURL: ''

# The username and password for the bot forum account.
ForumUsername: ''
ForumPassword: ''

# Name of the forum bot.
BotName: ''