#============ VerifyMe ============#

# Should Forum Verification be enabled?
ForumVerification: true

# The URL of the forums.
ForumURL: ''

# The username and password for the forum bot account.
ForumUsername: ''
ForumPassword: ''

# Name of the forum bot.
ForumBotName: ''

# Should Discord Verification be enabled?
DiscordVerification: true

# The token for the discord bot.
DiscordBotToken: ''