name: VerifyMe
main: com.commodore.verifyme.VerifyMe
version: 1.3
description: Plugin to verify admins on the TotalFreedom server
depend: [TotalFreedomMod]
author: Commodore64x

commands:
  verifyme:
    description: The main plugin command, displays information about the plugin.
    usage: "Usage: /verifyme"
  forum:
    description: The forum verification command, request or submit a verification token.
    usage: "Usage: /forum <linkaccount | unlinkaccount [admin]> <gettoken> || <verifytoken token> || <help>"
  discord:
    description: The discord verification command, request or submit a verification token.
    usage: "Usage: /discord <linkaccount | unlinkaccount [admin]> <gettoken> || <verifytoken token> || <help>"