name: VerifyMe
main: com.commodore.verifyme.VerifyMe
version: 1.0
description: Plugin to verify admins for the TotalFreedom Server
depend: [TotalFreedomMod]
author: Commodore64x

commands:
  forum:
    description: The forum verification command, request or submit a verification token.
    usage: "Usage: /forum <linkaccount | unlinkaccount [admin]> <gettoken> || <verifytoken token> || <help>"
  discord:
    description: The discord verification command, request or submit a verification token.
    usage: "Usage: /discord <linkaccount | unlinkaccount [admin]> <gettoken> || <verifytoken token> || <help>"